package find_the_difference;

/**
 * You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
 */

public class Solution {
    public char findTheDifference(String s, String t) {
        int[] counter = new int[26];
        for (int i = 0; i < t.length(); i++) {
            counter[t.charAt(i) - 'a']++;
        }
        for (int i = 0; i < s.length(); i++) {
            counter[s.charAt(i) - 'a']--;
        }
        char ans = 'a';
        for (int i = 0; i < counter.length; i++) {
            if(counter[i] != 0) ans = (char) (97 + i);
        }
        return ans;
    }
}
